name: Continuous integration build

on:
  push:
    branches: 
    - main 
    paths-ignore:
    - '**.md'
  pull_request:
    branches: 
    - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

    - name: Restore dependencies
      run: dotnet restore source/Cympatic.Stub.sln
    
    - name: Build
      run: dotnet build source/Cympatic.Stub.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test source/Cympatic.Stub.sln --configuration Release --no-build --verbosity normal 
