name: Continuous integration build

on:
  push:
    branches: 
    - main 
    paths-ignore:
    - '**.md'
  pull_request:
    branches: 
    - main 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            net6.0.x
            net7.0.x
            net8.0.x

    - name: Restore dependencies
      run: dotnet restore source/Server/Cympatic.Stub.sln
    
    - name: Build
      run: dotnet build source/Server/Cympatic.Stub.sln --no-restore
    
    - name: Test
      run: dotnet test source/Server/Cympatic.Stub.sln --no-build --verbosity normal 
